const breweries = {
    "Gulden Draak": "breweries/img/Belgium/Gulden_Draak.png",
    "Brasserie d'Achouffe": "breweries/img/Belgium/Achouffe.png",
    "Abbaye d'Aulne": "breweries/img/Belgium/Abbaye_dAulne.png",
    "Gaida": "breweries/img/Bulgaria/Gaida.png",
    "Kronenbourg": "breweries/img/France/Kronenbourg.png",
    "Mützig": "breweries/img/France/Mutzig.png",
    "Paulaner": "breweries/img/Germany/Paulaner.png",
    "Franziskaner": "breweries/img/Germany/Franziskaner.png",
    "Hofbräuhaus": "breweries/img/Germany/Hofbrauhaus.png",
    "Camba": "breweries/img/Germany/Camba.png",
    "Erdinger": "breweries/img/Germany/Erdinger.png",
    "Kaltenberg": "breweries/img/Germany/Kaltenberg.png",
    "Bischofshof": "breweries/img/Germany/Bischofshof.png",
    "Veltins": "breweries/img/Germany/Veltins.png",
    "Alpirsbacher": "breweries/img/Germany/Alpirsbacher.png",
    "Dom Kölsch": "breweries/img/Germany/Dom_Kolsch.png",
    "Kilkenny": "breweries/img/Ireland/Kilkenny.png",
    "Super Bock": "breweries/img/Portugal/SuperBock.png",
    "Alhambra": "breweries/img/Spain/Alhambra.png",
    "Estrella Galicia": "breweries/img/Spain/Estrella_Galicia.png",
    "Cruzcampo": "breweries/img/Spain/Cruzcampo.png",
    "El Aguila": "breweries/img/Spain/ElAguila.png",
    "Victoria Malaga": "breweries/img/Spain/Victoria.png",
    "Dorada": "breweries/img/Spain/Dorada.png",
    "Euro Pils": "breweries/img/Spain/EuroPils.png",
    "Spendrup's": "breweries/img/Sweden/Spendrups.png",
};