const breweries = {
    "Abbaye d'Aulne": "breweries/img/Belgium/Abbaye_dAulne.webp",
    "Affligem": "breweries/img/Belgium/Affligem.webp",
    "Brasserie d'Achouffe": "breweries/img/Belgium/Achouffe.webp",
    "Brugse Zot": "breweries/img/Belgium/Brugse_zot.webp",
    "De Koninck": "breweries/img/Belgium/De_Koninck.webp",
    "Grimbergen": "breweries/img/Belgium/Grimbergen.webp",
    "Gulden Draak": "breweries/img/Belgium/Gulden_Draak.webp",
    "Waterloo": "breweries/img/Belgium/Waterloo.webp",
    "Leffe": "breweries/img/Belgium/Leffe.webp",
    "Gaida": "breweries/img/Bulgaria/Gaida.webp",
    "Pilsner Urquell": "breweries/img/Czechia/Pilsner_urquell.webp",
    "Carlsberg": "breweries/img/Denmark/Carlsberg.webp",
    "Kronenbourg": "breweries/img/France/Kronenbourg.webp",
    "La Goudale": "breweries/img/France/La_Goudale.webp",
    "Mützig": "breweries/img/France/Mutzig.webp",
    "Paulaner": "breweries/img/Germany/Paulaner.webp",
    "Franziskaner": "breweries/img/Germany/Franziskaner.webp",
    "Hofbräuhaus": "breweries/img/Germany/Hofbrauhaus.webp",
    "Beck's": "breweries/img/Germany/Becks.webp",
    "Camba": "breweries/img/Germany/Camba.webp",
    "Erdinger": "breweries/img/Germany/Erdinger.webp",
    "Kaltenberg": "breweries/img/Germany/Kaltenberg.webp",
    "Bischofshof": "breweries/img/Germany/Bischofshof.webp",
    "Veltins": "breweries/img/Germany/Veltins.webp",
    "Alpirsbacher": "breweries/img/Germany/Alpirsbacher.webp",
    "Dom Kölsch": "breweries/img/Germany/Dom_Kolsch.webp",
    "Garde Kölsch": "breweries/img/Germany/Garde_Koelsch.webp",
    "Reissdorf Kölsch": "breweries/img/Germany/Reissdorf_Kolsch.webp",
    "Gereons Kölsch": "breweries/img/Germany/Gereons_Koelsch.webp",
    "Haake Beck": "breweries/img/Germany/Haake_Beck.webp",
    "Feldschlösschen": "breweries/img/Germany/Feldschloesschen.webp",
    "Grevensteiner": "breweries/img/Germany/Grevensteiner.webp",
    "Pils 2000": "breweries/img/Germany/Pils_2000.webp",
    "Brinkhoff's": "breweries/img/Germany/Brinkhoffs.webp",
    "Henninger": "breweries/img/Germany/Henninger.webp",
    "Kilkenny": "breweries/img/Ireland/Kilkenny.webp",
    "Guinness": "breweries/img/Ireland/Guinness.webp",
    "Heineken": "breweries/img/Netherlands/Heineken.webp",
    "La Trappe": "breweries/img/Netherlands/La_Trappe.webp",
    "Bavaria": "breweries/img/Netherlands/Bavaria.webp",
    "Buckler": "breweries/img/Netherlands/Buckler.webp",
    "Super Bock": "breweries/img/Portugal/SuperBock.webp",
    "Alhambra": "breweries/img/Spain/Alhambra.webp",
    "Estrella Galicia": "breweries/img/Spain/Estrella_Galicia.webp",
    "Cruzcampo": "breweries/img/Spain/Cruzcampo.webp",
    "El Aguila": "breweries/img/Spain/ElAguila.webp",
    "Victoria Malaga": "breweries/img/Spain/Victoria.webp",
    "Dorada": "breweries/img/Spain/Dorada.webp",
    "San Miguel": "breweries/img/Spain/San_Miguel.webp",
    "Euro Pils": "breweries/img/Spain/EuroPils.webp",
    "Arriaca": "breweries/img/Spain/Arriaca.webp",
    "Mahou": "breweries/img/Spain/Mahou.webp",
    "Ambar": "breweries/img/Spain/Ambar.webp",
    "Amstel Cerveza": "breweries/img/Spain/Amstel_Cerveza.webp",
    "3Monos": "breweries/img/Spain/3Monos.webp",
    "Legado de Yuste": "breweries/img/Spain/Legado_de_Yuste.webp",
    "La Sagra": "breweries/img/Spain/LaSagra.webp",
    "Spendrup's": "breweries/img/Sweden/Spendrups.webp",
    "Skol": "breweries/img/Scotland/Skol.webp",
    "Budweiser": "breweries/img/Usa/Budweiser.webp",
};