const breweries = {
    "Gulden Draak": "breweries/img/Belgium/Gulden_Draak.webp",
    "Brasserie d'Achouffe": "breweries/img/Belgium/Achouffe.webp",
    "Abbaye d'Aulne": "breweries/img/Belgium/Abbaye_dAulne.webp",
    "Gaida": "breweries/img/Bulgaria/Gaida.webp",
    "Carlsberg": "breweries/img/Denmark/Carlsberg.webp",
    "Kronenbourg": "breweries/img/France/Kronenbourg.webp",
    "Mützig": "breweries/img/France/Mutzig.webp",
    "Paulaner": "breweries/img/Germany/Paulaner.webp",
    "Franziskaner": "breweries/img/Germany/Franziskaner.webp",
    "Hofbräuhaus": "breweries/img/Germany/Hofbrauhaus.webp",
    "Camba": "breweries/img/Germany/Camba.webp",
    "Erdinger": "breweries/img/Germany/Erdinger.webp",
    "Kaltenberg": "breweries/img/Germany/Kaltenberg.webp",
    "Bischofshof": "breweries/img/Germany/Bischofshof.webp",
    "Veltins": "breweries/img/Germany/Veltins.webp",
    "Alpirsbacher": "breweries/img/Germany/Alpirsbacher.webp",
    "Dom Kölsch": "breweries/img/Germany/Dom_Kolsch.webp",
    "Garde Kölsch": "breweries/img/Germany/Garde_Koelsch.webp",
    "Reissdorf Kölsch": "breweries/img/Germany/Reissdorf_Kolsch.webp",
    "Gereons Kölsch": "breweries/img/Germany/Gereons_Koelsch.webp",
    "Haake Beck": "breweries/img/Germany/Haake_Beck.webp",
    "Feldschlösschen": "breweries/img/Germany/Feldschloesschen.webp",
    "Brinkhoff's": "breweries/img/Germany/Brinkhoffs.webp",
    "Henninger": "breweries/img/Germany/Henninger.webp",
    "Kilkenny": "breweries/img/Ireland/Kilkenny.webp",
    "Heineken": "breweries/img/Netherlands/Heineken.webp",
    "La Trappe": "breweries/img/Netherlands/La_Trappe.webp",
    "Super Bock": "breweries/img/Portugal/SuperBock.webp",
    "Alhambra": "breweries/img/Spain/Alhambra.webp",
    "Estrella Galicia": "breweries/img/Spain/Estrella_Galicia.webp",
    "Cruzcampo": "breweries/img/Spain/Cruzcampo.webp",
    "El Aguila": "breweries/img/Spain/ElAguila.webp",
    "Victoria Malaga": "breweries/img/Spain/Victoria.webp",
    "Dorada": "breweries/img/Spain/Dorada.webp",
    "San Miguel": "breweries/img/Spain/San_Miguel.webp",
    "Euro Pils": "breweries/img/Spain/EuroPils.webp",
    "Arriaca": "breweries/img/Spain/Arriaca.webp",
    "Amstel Cerveza": "breweries/img/Spain/Amstel_Cerveza.webp",
    "Spendrup's": "breweries/img/Sweden/Spendrups.webp",
};